control:
  leg_height: 0.24
command:
  linear_velocity: 0.8
  yaw_rate: 1.2
  spin_yaw_rate: 8.0
  linear_acceleration: 3.0
  yaw_acceleration: 6.0
  leg_length_velocity: 0.05
  leg_length_min: 0.2
  leg_length_max: 0.28
lqr:
  finite_difference_step: 1.0e-06
  control_limits:
    left_front_motor: 60.0
    left_rear_motor: 60.0
    right_front_motor: 60.0
    right_rear_motor: 60.0
    left_wheel_motor: 4.5
    right_wheel_motor: 4.5
    yaw_motor: 5.0
    pitch_motor: 5.0
  Q_weights:
    position:
      forward: 120.0
      height: 10000.0
      roll: 10000.0
      pitch: 3000.0
      heading: 100.0
      left_front_joint: 50.0
      left_rear_joint: 50.0
      right_front_joint: 50.0
      right_rear_joint: 50.0
      yaw_joint: 100.0
      pitch_joint: 100.0
    velocity:
      forward: 300.0
      height: 100.0
      roll: 50.0
      pitch: 100.0
      heading: 20.0
      left_front_joint: 1.0
      left_rear_joint: 1.0
      right_front_joint: 1.0
      right_rear_joint: 1.0
      left_wheel_joint: 0.1
      right_wheel_joint: 0.1
      yaw_joint: 1.0
      pitch_joint: 1.0
